name: Node.js CI/CD

on:
  push:
    branches: 
      - main  # Ejecutar cuando haya un push en la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --only=production  # Solo dependencias de producción
    - run: npm run build --if-present  # Construir el código si es necesario

  deploy:
    runs-on: ubuntu-latest
    needs: build  # El despliegue depende de que el trabajo de construcción se haya completado

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no dtidweb@200.4.136.110 'bash -s' < ./github/workflows/deploy.yml
