name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Ejecutar cuando haya un push en la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install  # Instalar todas las dependencias
    - run: npm run build --if-present  # Construir el código si es necesario

  deploy:
    runs-on: ubuntu-latest
    needs: build  # El despliegue depende de que el trabajo de construcción se haya completado

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH and Deploy to Production Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Configurar SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Comandos para desplegar directamente en el servidor
        ssh -o StrictHostKeyChecking=no dtidweb@200.4.136.110 << 'EOF'
          # Navegar al directorio del proyecto
          cd /var/www/html/AppUagroEjemplo/AppUagroNew || exit

          # Hacer pull del repositorio para tener la versión más reciente
          git pull origin main

          # Instalar dependencias solo de producción
          npm install --production

          # Ejecutar build si es necesario
          npm run build

          # Reiniciar la aplicación (esto depende de tu configuración de servidor, por ejemplo usando pm2)
          pm2 restart your-app-name || pm2 start your-app-name
        EOF
