name: Despliegue automatizado

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run-pull:
    name: run pull
    runs-on: self-hosted

    steps:
    # Paso 1: Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Usa la versión adecuada para tu proyecto
        cache: 'npm'

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: npm install

    # Paso 4: Compilar el proyecto
    - name: Build the project
      run: npm run build

    # Paso 5: Subir archivos al servidor remoto
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        TARGET_DIR: '/var/www/html/AppUagroEjemplo' # Cambia si necesitas otro directorio
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -avz --delete dist/ $SERVER_USERNAME@$SERVER_IP:$TARGET_DIR

    # Paso 6: Configurar Apache
    - name: Configure Apache
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP << 'EOF'
          sudo a2enmod rewrite
          sudo bash -c 'cat > /etc/apache2/sites-available/vite-app.conf' << CONFIG
          <VirtualHost *:80>
              ServerName 192.168.140.209 # Cambia por tu dominio
              DocumentRoot /var/www/html/AppUagroEjemplo

              <Directory /var/www/html/AppUagroEjemplo>
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/vite-error.log
              CustomLog ${APACHE_LOG_DIR}/vite-access.log combined
          </VirtualHost>
          CONFIG
          sudo a2ensite vite-app.conf
          sudo systemctl reload apache2
        EOF
